package com.crio.starter.entity;

import lombok. AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.Id;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;

/**
 * Entity class representing a Meme in the database
 * Uses MongoDB as the persistence layer
 */
@Data
@NoArgsConstructor
@AllArgsConstructor
@Document(collection = "memes")
public class Meme {
    
    /**
     * Unique identifier for the meme (auto-generated by MongoDB)
     */
    @Id
    private String id;
    
    /**
     * Name of the person who posted the meme
     */
    private String name;
    
    /**
     * URL of the meme image
     */
    private String url;
    
    /**
     * Caption/description for the meme
     */
    private String caption;
    
    /**
     * Timestamp when the meme was created
     */
    private LocalDateTime createdAt;
    
    /**
     * Timestamp when the meme was last updated
     */
    private LocalDateTime updatedAt;
}